### ISSUE TITLE
KeyError: 'TagPage'

### ISSUE THREAD

**Issue by h4rk8s** [FloweryK/crawler_instagram#1]
(layubitera) opening url: https://www.instagram.com/explore/tags/layubitera/
Traceback (most recent call last):
  File "tag_crawler.py", line 71, in <module>
    crawl(tag, limit)
  File "tag_crawler.py", line 38, in crawl
    edges = get_edges(html)
  File "/root/crawler_instagram/funcs.py", line 65, in get_edges
    edges = json_data['entry_data']['TagPage'][0]['graphql']['hashtag']['edge_hashtag_to_media']['edges']
KeyError: 'TagPage'

**Comment by FloweryK** [comment]
Works Fine for me:

$ python crawler.py --mode tag --target layubitera
(tags/layubitera) opening url: https://www.instagram.com/explore/tags/layubitera/
(tags/layubitera) 28 posts to be added (merged_results: 0)
(tags/layubitera) opening url: https://www.instagram.com/explore/tags/layubitera/?max_id=1948610021445341130
(tags/layubitera) end of query

Can you describe the process you're working on?? like, commands on bash, environment, etc
